string CLIENT_CONNECT = "CLIENT_CONNECT";
string SERVER_HEART_BEAT = "SERVER_HEART_BEAT";
string SERVER_HEART_BEAT_ACK = "CLIENT_ACK";
string USERSTORE_OPERATION_RESPONSE = "US_RESPONSE";

enum USERSTORE_OPERATIONS {
    DO_AUTHENTICATE
};
