final string CLIENT_CONNECT = "CLIENT_CONNECT";
final string SERVER_CONNECT = "SERVER_CONNECT";

// final string SERVER_HEART_BEAT = "SERVER_HEART_BEAT";
// final string CLIENT_HEART_BEAT_ACK = "CLIENT_ACK";

final string USERSTORE_OPERATION_RESPONSE = "US_RESPONSE";

enum USERSTORE_OPERATIONS {
    DO_AUTHENTICATE
};
