IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[AGENT_ACCESS_TOKEN]') AND TYPE IN (N'U'))

CREATE TABLE AGENT_ACCESS_TOKEN (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    TENANT VARCHAR(255) NOT NULL,
    DOMAIN VARCHAR(255) NOT NULL,
    UNIQUE (TOKEN),
    UNIQUE (TOKEN, TENANT),
    PRIMARY KEY (ID)
);

INSERT INTO AGENT_ACCESS_TOKEN (TOKEN, TENANT, [DOMAIN]) VALUES('0ff93c70d1eb86972e1b9ac69cc8540bf8acf5a2021fe9dbfb621bb8c793c74c', 'test_tenant_1', 'REMOTE1');
